# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: "weekly"
      day: 'saturday'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly' 
      day: 'saturday'
  - package-ecosystem: "custom"
    directory: '/'
    schedule:
      interval: 'weekly' 
      day: 'saturday'
    update_config:
      run:
        - command: curl https://trusted/upstream/source
        - command: ./local-update
        - command: git add deps*
        - command: git commit -m "sync with upstream"
        - command: git push

