version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated pr"
      - "non-owner pull request"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "automated pr"
      - "javascript"
      - "non-owner pull request"
    open-pull-requests-limit: 10
