name: Python Action
description: Quickly run your Python code and verify it is error-free
author: Jeremy Escobar
branding:
  icon: activity
  color: gray-dark
inputs:
  repo-token:
    description: Access token.
    required: false
  configuration-path:
    description: Path to configuration file.
    required: false
  sync-labels:
    description: Synchronize labels.
    default: false
  repository:
    description: 'Owner/repo name.'
    default: ${{ github.repository }}
  ref:
    description: Checkout reference.
    default: ${{ github.event.ref }}
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
