name: Python Action
description: Quickly run your Python code and verify it is error-free
author: Jeremy Escobar
branding:
  icon: activity
  color: gray-dark
inputs:
  input1:
    description: An input for the action
    required: true
outputs:
  output1:
    description: An output from the action
runs:
  shell: bash
  steps:
    - name: Checkout
      uses: jge162/Action-workflows@v0.0.6
    - name: Run Action
      run: |
        echo "Hello, world!"
