#!/bin/bash

# Set the API endpoint
ENDPOINT=https://api.github.com/actions

# Make a request to the GitHub Actions API endpoint
response=$(curl -s -H "Authorization: token $TOKEN" $ENDPOINT)

# Parse the response to check the status of the API
status=$(echo $response | jq '.status')

# Print the status of the API
echo "GitHub Actions API status: $status"
