name: 'Assign reviewers'

on:
  pull_request:
    types: [opened]
    
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Assign reviewers
        if: ${{ github.actor != 'jge162' }}
        uses: TheoNoyau/assign-reviewers-action@v1.0
        with:
          who-to-assign: jge162 jge162
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
