name: "Assign Reviewers to PR"

on:  
  pull_request:
    types: [opened, ready_for_review, reopened, review_requested, review_request_removed]
     
jobs:
  assign-pr-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Reviewers to PR"
      if: github.actor == 'jge162'
      uses: itsOliverBott/assign-pr-reviewers@release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        users: "geo4u" # comma-separated (example: "itsOliverBott, SantaClaus, b4tman, sp0derman")
        ignore-drafts: true # defaults to false if not provided
