name: PRs auto merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.3.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'squash' # Default 'squash'
        min-approvals: 0 # No approvals needed
        base-ref: 'main' # Default 'main'
