on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewer
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: jge162
          assignees: jge162
          skipKeywords: wip, draft 
          addReviewers: true
          addAssignees: true
          numberOfReviewers: 1
          numberOfAssignees: 1
          skipDraft: true
