
name: Geo4u & Dr. Nefardio auto-approve
# auto_aprove_geo4u
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'geo4u' || github.actor == 'dr-nefardio3058' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        # uses: dependabot/fetch-metadata@v1
        uses: jge162/Action-workflows@1.1.1
        with:
          token: "${{ secrets.WORKFLOW_SECRET }}" # <-- Updated
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          token: "${{ secrets.WORKFLOW_SECRET }}" # <-- Updated
