on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 
          assignees: jge162
          skipKeywords: wip, draft 
          addReviewers: false
          addAssignees: true
          numberOfReviewers: 0
          numberOfAssignees: 1
          skipDraft: true
