name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.WORKFLOW_SECRET }}"
      - name: Enable auto-merge for Dependabot PRs
          #if (contains(steps.metadata.outputs.dependency-names, 'actions/stale') || 
          #contains(steps.metadata.outputs.dependency-names, '@zeit/ncc') || 
          #contains(steps.metadata.outputs.dependency-names, 'ts-jest') || 
          #contains(steps.metadata.outputs.dependency-names, 'uuid') || 
          #contains(steps.metadata.outputs.dependency-names, 'jest-circus') || 
          #(contains(steps.metadata.outputs.dependency-names, 'actions/github-script') && 
          #steps.metadata.outputs.update-type == 'version-update:semver-major'))
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.WORKFLOW_SECRET}}

  Changelog_Enforcer:
    runs-on: ubuntu-latest44
    needs: [dependabot]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Get pull request number
        id: get_pull_request_number
        run: echo "::set-output name=pull_request_number::${{ github.event.number }}"

      - name: Generate changelog
        run: |
          npx npm-changelog --stdout --tag-format="{{version}} Pull Request: #${{ steps.get_pull_request_number.outputs.pull_request_number }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "This was a dependabot, automated update" >> CHANGELOG.md

      - name: Commit updated changelog
        run: |
          git config --global user.email "daubers_heights.0h@icloud.com"
          git config --global user.name "Jeremy Escobar"
          git add CHANGELOG.md
          git commit -m "chore: update changelog" --no-verify
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
