name: Auto Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited, ready_for_review, unlocked]

jobs:
  merge-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required label and branch
        if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.event.pull_request.base.ref == 'main'
        run: |
          echo "PR meets requirements, ready to merge"
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
