name: Geo4u & Dr. Nefardio auto-approve
# auto_aprove_geo4u
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'geo4u' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        # uses: dependabot/fetch-metadata@v1
        uses: jge162/Action-workflows@1.1.1
        with:
          github-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Approve a PR
        run: |
          export GH_TOKEN="${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
