name: Auto Merge by User
on:
  pull_request_target:
    types: [labeled]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    # Specifically check that jge162 (or another trusted party) created this pull-request, and that it has been labelled correctly.
    if: github.event.pull_request.user.login == 'jge162' && contains(github.event.pull_request.labels.*.name, 'enhancement')
    steps:
    - name: Enable Auto Merge
      uses: peter-evans/auto-merge@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        label: "enhancement"
        author: "jge162"



