name: Changelog enforcer
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronized
    - labeled
    - unlabeled
jobs:
  check_pr_size:
    runs-on: ubuntu-latest
    steps:
    - uses: guzzler/file-changelog-issue-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
