name: Pull Request Changelog

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract latest version from changelog
        id: latest_version
        run: |
          latest_version=$(grep -E '## [vV]?[0-9]+\.[0-9]+\.[0-9]+(-.*)?' CHANGELOG.md | head -n 1 | awk -F'[][]' '{print $2}')
          echo "::set-output name=latest_version::${latest_version}"

  add-changelog-entry:
    needs: [get-latest-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request details
        id: get_pr
        run: |
          echo ::set-output name=pr_number::${{ github.event.pull_request.number }}
          echo ::set-output name=pr_title::${{ github.event.pull_request.title }}
          echo ::set-output name=pr_author::${{ github.event.pull_request.user.login }}

      - name: Update changelog file
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          latest-version: ${{ needs.get-latest-version.outputs.latest_version }}
          release-notes: |
            ### PR #${{ steps.get_pr.outputs.pr_number }}: ${{ steps.get_pr.outputs.pr_title }} [${{ steps.get_pr.outputs.pr_author }}]

            # Describe the changes made in the pull request here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
