name: Update Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enforce changelog entry
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGELOG.md'
          expectedLatestVersion: '${{ github.ref }}'

      - name: Update changelog file
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            const changelogEntry = `## [${{ github.ref }}] - ${new Date().toISOString().split('T')[0]}\n\n${{ steps.changelog.outputs.changelog }}\n`;
            fs.appendFileSync('CHANGELOG.md', changelogEntry);

          # Set the token for authentication to the GitHub API
          # It is recommended to use a Personal Access Token with the 'repo' scope instead of the default GITHUB_TOKEN
          # This is because GITHUB_TOKEN does not have the permissions to push changes to the repository
          # See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token for instructions on how to create a Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
