name: Changelog Automation

on:
  push:
    branches:
      - main
      # - release/**

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Merge')"
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3
        
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install -g yarn

      - name: Get Title PR
        id: get_message
        run: echo "::set-output name=MESSAGE::$(echo '${{github.event.head_commit.message}}' | tail -n 1)"

      - name: Update Changelog
        uses: ./
        with:
          changelog_new_log: ${{ steps.get_message.outputs.MESSAGE }}
          log_find: '## Alterações'
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
