name: comment_on_pullrequest

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: comment_on_pullrequest
        uses: mshick/add-pr-comment@v2
        with:
          if: always()
          message: |
            $(cat .github/workflows/PULL_REQUEST_TEMPLATE.md)
          message-failure: |
            Uh oh!
