name: Comment_on_pullrequest

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment_on_pullrequest
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Description
            Please include a summary of the change and which issue is fixed. 
            Please also include relevant motivation and context. 
            List any dependencies that are required for this change.
            ## Type of change
            - [ ] Bug fix (non-breaking change which fixes an issue)
            - [ ] New feature (non-breaking change which adds functionality)
            ## Checklist:
            - [ ] My code follows the style guidelines of this project
            - [ ] I have performed a self-review of my own code
            - [ ] I have commented my code, particularly in hard-to-understand areas
            - [ ] My changes generate no new warnings
            - [ ] I have added tests that prove my fix is effective or that my feature works
          message-failure: |
            Uh oh!
          message-id: add-pr-comment
          repo-token: ${{ secrets.WORKFLOW_SECRET }}
          allow-repeats: true
          status: success
