name: comment_on_pullrequest

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: comment_on_pullrequest
        uses: mshick/add-pr-comment@v2
        with:
          if: always()
          message: |
            **Thank you for the Pull Request! Please let me know what changes you have in mind!**
          message-failure: |
            Uh oh!
