name: Comment_on_pullrequest

on:
  pull_request:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment_on_pullrequest
        if: github.event.pull_request.user.login == 'jge162'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## Description
            - [ ] Please include a summary of the change and/or which issues have been fixed. 
          message-failure: |
            Uh oh!
          message-id: add-pr-comment
          repo-token: ${{ secrets.WORKFLOW_SECRET }}
          allow-repeats: true
          status: success
