name: Release on Pull Request Close

on:
  pull_request:
    types: [closed]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'create release') && github.event.pull_request.user.login == 'jge162'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git tag v0.0.1
          git push --tags
          git fetch --tags
          echo "::set-output name=latest_tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
      - name: Bump version
        id: bump_version
        run: |
          semver=( ${steps.get_latest_tag.outputs.latest_tag//./ } )
          major=${semver[0]}
          minor=${semver[1]}
          patch=${semver[2]}
          new_patch=$((patch+1))
          new_tag="$major.$minor.$new_patch"
          echo "::set-output name=new_tag::$new_tag"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          body: |
            This is the release notes for ${steps.bump_version.outputs.new_tag}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SECRET }}
