name: GitHub Status

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 1 AM UTC every day
  workflow_dispatch:
  
jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create API directory
        run: mkdir -p ./resources/API

      - name: Create check_api_status.sh script
        run: touch ./resources/API/check_api_status.sh

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check API Status
        run: |
          cd ./resources/API
          response=$(curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json)
          status=$(echo $response | jq -r '.status.indicator')
          echo -e "\n$(date): GitHub Actions API status: $status" >> ../../resources/COMMITLOG.md
        env:
          TOKEN: ${{ secrets.WORKFLOW_SECRET }}

      - name: Count Commits
        run: |
          commit_count=$(git rev-list --count HEAD --author="<jge162>" --since="1 week ago")
          echo "Commit count: $commit_count"

      - name: Commit changes
        run: |
          commit_count=$(git log --oneline --author="<jge162>" --since="1 week ago" | wc -l)
          if [[ $commit_count -lt 4 ]]; then
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "<jge162>"
            git add .
            git commit -m "Automated commit: Update API status in commitlog"
            git push
          else
            echo "Already committed 4 times this week. Skipping commit."
          fi
