name: GitHub Status

on:
  schedule:
    - cron: '0 1 1,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30 * *' 
    # Runs at 1 AM UTC on the 1st, 2nd, 4th, 6th, 8th, 10th, 12th, 14th, 16th, 18th, 20th, 22nd, 24th, 26th, 28th, and 30th day of each month
  workflow_dispatch:
  
jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      # Steps for checking API status and committing changes...
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create API directory
        run: mkdir -p ./resources/API

      - name: Create check_api_status.sh script
        run: touch ./resources/API/check_api_status.sh

      - name: Install jq
        run: sudo apt-get install jq
          
      - name: Check API Status
        run: |
          cd ./resources/API
          response=$(curl -s https://kctbh9vrtdwd.statuspage.io/api/v2/status.json)
          status=$(echo $response | jq -r '.status.indicator')
          echo -e "\n$(date): GitHub Actions API status: $status" >> ../../resources/COMMITLOG.md
        env:
          TOKEN: ${{ secrets.WORKFLOW_SECRET }}

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "<jge162>"
          git add .
          git commit -m "Automated commit: Update API status in commitlog"
          git push
