name: Comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment_on_new_issue:
    runs-on: ubuntu-latest
    name: Job for commenting on new issue
    steps:
      - name: Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: github.event.issue.number,
              repo: github.repository.name,
              owner: github.repository.owner.login,
              body: "Thanks for opening this issue! I'll take a look and get back to you soon."
            });
