name: Comment on new issue
on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Issue comment
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: issue comment
        uses: kyoncy/issue-comment-actions@v1
        with:
          message: "Thank you for opening this issue, I'll take a look and get back to you soon."
          # testing

