name: Issue Assigner

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  issue_assigner:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Assigner
        uses: kbrashears5/github-action-issue-assigner@v1.0.0
        with:
          TOKEN: ${{ secrets.TOKEN }}
