name: Comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment_on_new_issue:
    runs-on: ubuntu-latest
    name: Job for commenting on new issue
    steps:
      - name: Comment
        uses: jd-0001/gh-action-comment-on-new-issue@v2.0.3
        with:
          message: 'Welcome to the repo! Please provide more details about the issue you are facing.'
          ignore-label: 'internal'
