name: Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
      
    - name: Issue comment
      uses: kyoncy/issue-comment-actions@v1
      with:
        message: Thank you for opening this issue, I'll take a look and get back to you soon.
        token: ${{ secrets.GITHUB_TOKEN }}
