on:
  pull_request_target

jobs:
  triage:
    if: ${{ not(eq(github.actor, 'jge162')) }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflows/labeler.yml
        sync-labels: false
