name: Label owner 

on:
  pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Debug information
      run: echo "User login: ${{ github.event.pull_request.user.login }}"
    - name: Label owner
      if: ${{ (github.event.pull_request.user.login == 'jge162') }}
      uses: actions/labelers@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeled.yml
        sync-labels: false
    - name: Label not owner
      if: ${{ (github.event.pull_request.user.login != 'jge162') }}
      uses: actions/labelers@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labelers.yml
        sync-labels: false
