name: auto-approve-jge162
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'jge162' }}
    steps:
      - name: Owner approved metadata
        id: metadata
        uses: jge162/Action-workflows@main
        with:
          github-token: "${{ secrets.WORKFLOW_SECRET }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.WORKFLOW_SECRET}}
