name: Run script on new commit

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      uses: actions/run-script@v1
      with:
        script: ./CommitScript.sh
