name: Run Script
on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Script
      run: |
        echo "Run, Build Application using scripts"
        COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
        echo "Commit message: $COMMIT_MESSAGE"
        dash ./CommitScript.sh "$COMMIT_MESSAGE"
        
