name: rerun Pull Requests
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if rerun is requested
        run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') }}" >> $GITHUB_ENV
      - name: Check if pull request
        if: github.event_name == 'pull_request'
        run: echo "RUN_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Rerun workflow
        if: env.RERUN == 'true'
        run: echo "Rerunning workflow"
        env:
          RUN_ID: ${{ github.run_id }}
