name: rerun Pull Requests
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if rerun is requested
        run: echo "RERUN=${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'rerun build') }}" >> $GITHUB_ENV
      - name: Check if pull request
        if: github.event_name == 'pull_request'
        run: echo "RUN_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Rerun workflow
        if: env.RERUN == 'true'
        run: echo "Rerunning workflow"
        env:
          RUN_ID: ${{ github.run_id }}
  
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Label owner
      if: ${{ (github.event.pull_request.user.login == 'jge162') }}
      # if owner label, owner puled
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeled.yml
        sync-labels: false
    - name: Label not owner
      if: ${{ (github.event.pull_request.user.login != 'jge162') }}
      # if anyone else besides owner, non-owner label
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labelers.yml
        sync-labels: false
