name: My GitHub Action

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "common/**"
      - "myservice/**"
    if: "!startsWith(github.ref, 'refs/tags/')"

  push:
    tags:
      - "*"
    branches:
      - main
    if: "startsWith(github.ref, 'refs/tags/')"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run my command
        run: |
          # Add your command here
