name: Respond to Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  respond:
    runs-on: ubuntu-latest
    
    steps:
      - name: Respond to Pull Request
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (github.event.pull_request) {
              github.issues.createComment({
                issue_number: github.event.pull_request.number,
                repo: github.repository.name,
                owner: github.repository.owner.login,
                body: "Thanks for opening this pull request! I'll take a look and get back to you soon."
              });
            }
