on:
  pull_request:
    types:
      - opened

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Leave a comment on pull request
      if: ${{ github.event.pull_request }}
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: github.event.pull_request.number,
            owner: github.repository.owner.login,
            repo: github.repository.name,
            body: "Thank you for submitting this pull request! I will review it soon."
          });
