name: Run VHDL code

on: 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup GHDL
        uses: ghdl/setup-ghdl-ci@master
      - name: Run VHDL code
        run: ghdl -r --std=08 testbench --vcd=waveform.vcds
