name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to my REPO!, **This is your first time here.** Can you briefly discribe the issue you found and/or bug please. Thank you."
        pr-message: "Welcome to my REPO!, **This is your first time here.** Thanks for the pull rquest. Let me know what you have changed. Thanks."
